// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t *ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen_StartScreen_screen_init();
ui_Screen_HomeScreen_screen_init();
ui_Screen_PrayersScreen_screen_init();
ui_Screen_SettingsScreen_screen_init();
ui_Screen_AzanScreen_screen_init();
ui_Startevents____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen_StartScreen);
}

void ui_destroy( void )
{ui_Screen_StartScreen_screen_destroy();
ui_Screen_HomeScreen_screen_destroy();
ui_Screen_PrayersScreen_screen_destroy();
ui_Screen_SettingsScreen_screen_destroy();
ui_Screen_AzanScreen_screen_destroy();
}
