// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT SystemLoadingLabel

lv_obj_t *ui_Label_SystemLoadingLabel_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Label_SystemLoadingLabel;
cui_Label_SystemLoadingLabel = lv_label_create(comp_parent);
lv_obj_set_width( cui_Label_SystemLoadingLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label_SystemLoadingLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_Label_SystemLoadingLabel, 0 );
lv_obj_set_y( cui_Label_SystemLoadingLabel, -14 );
lv_obj_set_align( cui_Label_SystemLoadingLabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label_SystemLoadingLabel,"System wird gestartet...");
ui_object_set_themeable_style_property(cui_Label_SystemLoadingLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(cui_Label_SystemLoadingLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SYSTEMLOADINGLABEL_NUM);
children[UI_COMP_SYSTEMLOADINGLABEL_LABEL_SYSTEMLOADINGLABEL] = cui_Label_SystemLoadingLabel;
lv_obj_add_event_cb(cui_Label_SystemLoadingLabel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Label_SystemLoadingLabel, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Label_SystemLoadingLabel_create_hook(cui_Label_SystemLoadingLabel);
return cui_Label_SystemLoadingLabel; 
}

