// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_SYSTEMLOADINGLABEL_H
#define _UI_COMP_SYSTEMLOADINGLABEL_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT SystemLoadingLabel
#define UI_COMP_SYSTEMLOADINGLABEL_LABEL_SYSTEMLOADINGLABEL 0
#define _UI_COMP_SYSTEMLOADINGLABEL_NUM 1
lv_obj_t *ui_Label_SystemLoadingLabel_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
