// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen_AzanScreen = NULL;lv_obj_t *ui_AzanScreen_Container_Container14 = NULL;lv_obj_t *ui_AzanScreen_Label_PrayerTitle = NULL;lv_obj_t *ui_AzanScreen_Label_Label8 = NULL;
// event funtions

// build funtions

void ui_Screen_AzanScreen_screen_init(void)
{
ui_Screen_AzanScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_AzanScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Screen_AzanScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_background);
ui_object_set_themeable_style_property(ui_Screen_AzanScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_background);

ui_AzanScreen_Container_Container14 = lv_obj_create(ui_Screen_AzanScreen);
lv_obj_remove_style_all(ui_AzanScreen_Container_Container14);
lv_obj_set_width( ui_AzanScreen_Container_Container14, 295);
lv_obj_set_height( ui_AzanScreen_Container_Container14, 183);
lv_obj_set_align( ui_AzanScreen_Container_Container14, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_AzanScreen_Container_Container14,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_AzanScreen_Container_Container14, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_AzanScreen_Container_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_AzanScreen_Container_Container14, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_AzanScreen_Container_Container14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AzanScreen_Label_PrayerTitle = lv_label_create(ui_AzanScreen_Container_Container14);
lv_obj_set_width( ui_AzanScreen_Label_PrayerTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AzanScreen_Label_PrayerTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AzanScreen_Label_PrayerTitle, -105 );
lv_obj_set_y( ui_AzanScreen_Label_PrayerTitle, -99 );
lv_obj_set_align( ui_AzanScreen_Label_PrayerTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_AzanScreen_Label_PrayerTitle,"Asr");
ui_object_set_themeable_style_property(ui_AzanScreen_Label_PrayerTitle, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_primary);
ui_object_set_themeable_style_property(ui_AzanScreen_Label_PrayerTitle, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_primary);
lv_obj_set_style_text_font(ui_AzanScreen_Label_PrayerTitle, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AzanScreen_Label_Label8 = lv_label_create(ui_AzanScreen_Container_Container14);
lv_obj_set_width( ui_AzanScreen_Label_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AzanScreen_Label_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AzanScreen_Label_Label8, -126 );
lv_obj_set_y( ui_AzanScreen_Label_Label8, -66 );
lv_obj_set_align( ui_AzanScreen_Label_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_AzanScreen_Label_Label8,"Tippen zum Stoppen");
ui_object_set_themeable_style_property(ui_AzanScreen_Label_Label8, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_secondary);
ui_object_set_themeable_style_property(ui_AzanScreen_Label_Label8, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_secondary);
lv_obj_set_style_text_font(ui_AzanScreen_Label_Label8, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen_AzanScreen_screen_destroy(void)
{
   if (ui_Screen_AzanScreen) lv_obj_del(ui_Screen_AzanScreen);

// NULL screen variables
ui_Screen_AzanScreen= NULL;
ui_AzanScreen_Container_Container14= NULL;
ui_AzanScreen_Label_PrayerTitle= NULL;
ui_AzanScreen_Label_Label8= NULL;

}
