// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN_SETTINGSSCREEN_H
#define UI_SCREEN_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_SettingsScreen
extern void ui_Screen_SettingsScreen_screen_init(void);
extern void ui_Screen_SettingsScreen_screen_destroy(void);
extern lv_obj_t *ui_Screen_SettingsScreen;
extern lv_obj_t *ui_SettingsScreen_Container_Container18;
extern lv_obj_t *ui_SettingsScreen_Button_ResetButton2;
extern lv_obj_t *ui_SettingsScreen_Label_Label5;
extern lv_obj_t *ui_SettingsScreen_Button_HomeButton;
extern lv_obj_t *ui_SettingsScreen_Label_Label3;
extern lv_obj_t *ui_SettingsScreen_Container_Container11;
extern lv_obj_t *ui_SettingsScreen_Label_SeetingsTitle;
extern lv_obj_t *ui_SettingsScreen_Label_Label6;
extern lv_obj_t *ui_SettingsScreen_Container_Container13;
extern lv_obj_t *ui_SettingsScreen_Button_SoundMinusButton;
extern lv_obj_t *ui_SettingsScreen_Label_Label9;
extern lv_obj_t *ui_SettingsScreen_Label_SoundLevelLabel;
extern lv_obj_t *ui_SettingsScreen_Button_SoundPlusButton1;
extern lv_obj_t *ui_SettingsScreen_Label_Label7;
extern lv_obj_t *ui_SettingsScreen_Switch_Theme;
extern lv_obj_t *ui_SettingsScreen_Switch_Theme_Label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

