// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN_AZANSCREEN_H
#define UI_SCREEN_AZANSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_AzanScreen
extern void ui_Screen_AzanScreen_screen_init(void);
extern void ui_Screen_AzanScreen_screen_destroy(void);
extern lv_obj_t *ui_Screen_AzanScreen;
extern lv_obj_t *ui_AzanScreen_Container_Container14;
extern lv_obj_t *ui_AzanScreen_Label_PrayerTitle;
extern lv_obj_t *ui_AzanScreen_Label_Label8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

