// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_SettingsScreen_Switch_Theme_Label = NULL;lv_obj_t *ui_SettingsScreen_Switch_Theme = NULL;lv_obj_t *ui_Screen_SettingsScreen = NULL;lv_obj_t *ui_SettingsScreen_Container_Container18 = NULL;lv_obj_t *ui_SettingsScreen_Button_ResetButton2 = NULL;lv_obj_t *ui_SettingsScreen_Label_Label5 = NULL;lv_obj_t *ui_SettingsScreen_Button_HomeButton = NULL;lv_obj_t *ui_SettingsScreen_Label_Label3 = NULL;lv_obj_t *ui_SettingsScreen_Container_Container11 = NULL;lv_obj_t *ui_SettingsScreen_Label_SeetingsTitle = NULL;lv_obj_t *ui_SettingsScreen_Label_Label6 = NULL;lv_obj_t *ui_SettingsScreen_Container_Container13 = NULL;lv_obj_t *ui_SettingsScreen_Button_SoundMinusButton = NULL;lv_obj_t *ui_SettingsScreen_Label_Label9 = NULL;lv_obj_t *ui_SettingsScreen_Label_SoundLevelLabel = NULL;lv_obj_t *ui_SettingsScreen_Button_SoundPlusButton1 = NULL;lv_obj_t *ui_SettingsScreen_Label_Label7 = NULL;lv_obj_t *ui_SettingsScreen_Container_ThemeRow = NULL;lv_obj_t *ui_SettingsScreen_Container_AdhanRow = NULL;lv_obj_t *ui_SettingsScreen_Label_AdhanLabel = NULL;lv_obj_t *ui_SettingsScreen_Button_AdhanChangeButton = NULL;lv_obj_t *ui_SettingsScreen_Label_AdhanChangeLabel = NULL;
// event funtions

// build funtions

void ui_Screen_SettingsScreen_screen_init(void)
{
ui_Screen_SettingsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Screen_SettingsScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_background);
ui_object_set_themeable_style_property(ui_Screen_SettingsScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_background);

ui_SettingsScreen_Container_Container18 = lv_obj_create(ui_Screen_SettingsScreen);
lv_obj_remove_style_all(ui_SettingsScreen_Container_Container18);
lv_obj_set_height( ui_SettingsScreen_Container_Container18, 37);
lv_obj_set_width( ui_SettingsScreen_Container_Container18, lv_pct(95));
lv_obj_set_x( ui_SettingsScreen_Container_Container18, 0 );
lv_obj_set_y( ui_SettingsScreen_Container_Container18, 94 );
lv_obj_set_align( ui_SettingsScreen_Container_Container18, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsScreen_Container_Container18,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsScreen_Container_Container18, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SettingsScreen_Container_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_SettingsScreen_Container_Container18, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SettingsScreen_Container_Container18, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsScreen_Button_ResetButton2 = lv_btn_create(ui_SettingsScreen_Container_Container18);
lv_obj_set_width( ui_SettingsScreen_Button_ResetButton2, 90);
lv_obj_set_height( ui_SettingsScreen_Button_ResetButton2, 33);
lv_obj_set_x( ui_SettingsScreen_Button_ResetButton2, -91 );
lv_obj_set_y( ui_SettingsScreen_Button_ResetButton2, 96 );
lv_obj_set_align( ui_SettingsScreen_Button_ResetButton2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsScreen_Button_ResetButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SettingsScreen_Button_ResetButton2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_ResetButton2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_background);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_ResetButton2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_background);
lv_obj_set_style_border_color(ui_SettingsScreen_Button_ResetButton2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SettingsScreen_Button_ResetButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SettingsScreen_Button_ResetButton2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SettingsScreen_Button_ResetButton2, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_SettingsScreen_Button_ResetButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SettingsScreen_Button_ResetButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsScreen_Label_Label5 = lv_label_create(ui_SettingsScreen_Button_ResetButton2);
lv_obj_set_width( ui_SettingsScreen_Label_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsScreen_Label_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsScreen_Label_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsScreen_Label_Label5,"Reset");
lv_obj_set_style_text_color(ui_SettingsScreen_Label_Label5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SettingsScreen_Label_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsScreen_Button_HomeButton = lv_btn_create(ui_SettingsScreen_Container_Container18);
lv_obj_set_width( ui_SettingsScreen_Button_HomeButton, 119);
lv_obj_set_height( ui_SettingsScreen_Button_HomeButton, 33);
lv_obj_set_x( ui_SettingsScreen_Button_HomeButton, 101 );
lv_obj_set_y( ui_SettingsScreen_Button_HomeButton, 96 );
lv_obj_set_align( ui_SettingsScreen_Button_HomeButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsScreen_Button_HomeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SettingsScreen_Button_HomeButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_HomeButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_background);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_HomeButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_background);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_HomeButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_primary);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_HomeButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_primary);
lv_obj_set_style_border_width(ui_SettingsScreen_Button_HomeButton, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SettingsScreen_Button_HomeButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_HomeButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_primary);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_HomeButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_primary);

ui_SettingsScreen_Label_Label3 = lv_label_create(ui_SettingsScreen_Button_HomeButton);
lv_obj_set_width( ui_SettingsScreen_Label_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsScreen_Label_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsScreen_Label_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsScreen_Label_Label3,"Back to Home");

ui_SettingsScreen_Container_Container11 = lv_obj_create(ui_Screen_SettingsScreen);
lv_obj_remove_style_all(ui_SettingsScreen_Container_Container11);
lv_obj_set_width( ui_SettingsScreen_Container_Container11, 295);
lv_obj_set_height( ui_SettingsScreen_Container_Container11, 183);
lv_obj_set_x( ui_SettingsScreen_Container_Container11, 0 );
lv_obj_set_y( ui_SettingsScreen_Container_Container11, -18 );
lv_obj_set_align( ui_SettingsScreen_Container_Container11, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsScreen_Container_Container11,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_SettingsScreen_Container_Container11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SettingsScreen_Container_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_SettingsScreen_Container_Container11, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SettingsScreen_Container_Container11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsScreen_Label_SeetingsTitle = lv_label_create(ui_SettingsScreen_Container_Container11);
lv_obj_set_width( ui_SettingsScreen_Label_SeetingsTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsScreen_Label_SeetingsTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SettingsScreen_Label_SeetingsTitle, -105 );
lv_obj_set_y( ui_SettingsScreen_Label_SeetingsTitle, -99 );
lv_obj_set_align( ui_SettingsScreen_Label_SeetingsTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsScreen_Label_SeetingsTitle,"Settings");
ui_object_set_themeable_style_property(ui_SettingsScreen_Label_SeetingsTitle, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_SettingsScreen_Label_SeetingsTitle, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_font(ui_SettingsScreen_Label_SeetingsTitle, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsScreen_Label_Label6 = lv_label_create(ui_SettingsScreen_Container_Container11);
lv_obj_set_width( ui_SettingsScreen_Label_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsScreen_Label_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SettingsScreen_Label_Label6, -126 );
lv_obj_set_y( ui_SettingsScreen_Label_Label6, -66 );
lv_obj_set_align( ui_SettingsScreen_Label_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsScreen_Label_Label6,"Ton");
ui_object_set_themeable_style_property(ui_SettingsScreen_Label_Label6, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_SettingsScreen_Label_Label6, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_font(ui_SettingsScreen_Label_Label6, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsScreen_Container_Container13 = lv_obj_create(ui_SettingsScreen_Container_Container11);
lv_obj_remove_style_all(ui_SettingsScreen_Container_Container13);
lv_obj_set_width( ui_SettingsScreen_Container_Container13, lv_pct(100));
lv_obj_set_height( ui_SettingsScreen_Container_Container13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsScreen_Container_Container13, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsScreen_Container_Container13,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsScreen_Container_Container13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SettingsScreen_Container_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_SettingsScreen_Container_Container13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SettingsScreen_Container_Container13, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsScreen_Button_SoundMinusButton = lv_btn_create(ui_SettingsScreen_Container_Container13);
lv_obj_set_width( ui_SettingsScreen_Button_SoundMinusButton, 45);
lv_obj_set_height( ui_SettingsScreen_Button_SoundMinusButton, 45);
lv_obj_set_x( ui_SettingsScreen_Button_SoundMinusButton, 101 );
lv_obj_set_y( ui_SettingsScreen_Button_SoundMinusButton, 96 );
lv_obj_set_align( ui_SettingsScreen_Button_SoundMinusButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsScreen_Button_SoundMinusButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SettingsScreen_Button_SoundMinusButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_SoundMinusButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_background);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_SoundMinusButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_background);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_SoundMinusButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_SoundMinusButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_title);
lv_obj_set_style_border_width(ui_SettingsScreen_Button_SoundMinusButton, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SettingsScreen_Button_SoundMinusButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_SoundMinusButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_primary);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_SoundMinusButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_primary);

ui_SettingsScreen_Label_Label9 = lv_label_create(ui_SettingsScreen_Button_SoundMinusButton);
lv_obj_set_width( ui_SettingsScreen_Label_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsScreen_Label_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsScreen_Label_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsScreen_Label_Label9,"-");
ui_object_set_themeable_style_property(ui_SettingsScreen_Label_Label9, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_SettingsScreen_Label_Label9, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_font(ui_SettingsScreen_Label_Label9, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsScreen_Label_SoundLevelLabel = lv_label_create(ui_SettingsScreen_Container_Container13);
lv_obj_set_width( ui_SettingsScreen_Label_SoundLevelLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsScreen_Label_SoundLevelLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsScreen_Label_SoundLevelLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsScreen_Label_SoundLevelLabel,"2");
ui_object_set_themeable_style_property(ui_SettingsScreen_Label_SoundLevelLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_SettingsScreen_Label_SoundLevelLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_font(ui_SettingsScreen_Label_SoundLevelLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsScreen_Button_SoundPlusButton1 = lv_btn_create(ui_SettingsScreen_Container_Container13);
lv_obj_set_width( ui_SettingsScreen_Button_SoundPlusButton1, 45);
lv_obj_set_height( ui_SettingsScreen_Button_SoundPlusButton1, 45);
lv_obj_set_x( ui_SettingsScreen_Button_SoundPlusButton1, 101 );
lv_obj_set_y( ui_SettingsScreen_Button_SoundPlusButton1, 96 );
lv_obj_set_align( ui_SettingsScreen_Button_SoundPlusButton1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsScreen_Button_SoundPlusButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SettingsScreen_Button_SoundPlusButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_SoundPlusButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_background);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_SoundPlusButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_background);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_SoundPlusButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_SoundPlusButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_title);
lv_obj_set_style_border_width(ui_SettingsScreen_Button_SoundPlusButton1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SettingsScreen_Button_SoundPlusButton1, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_SoundPlusButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_primary);
ui_object_set_themeable_style_property(ui_SettingsScreen_Button_SoundPlusButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_primary);

ui_SettingsScreen_Label_Label7 = lv_label_create(ui_SettingsScreen_Button_SoundPlusButton1);
lv_obj_set_width( ui_SettingsScreen_Label_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsScreen_Label_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsScreen_Label_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsScreen_Label_Label7,"+");
ui_object_set_themeable_style_property(ui_SettingsScreen_Label_Label7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_SettingsScreen_Label_Label7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_font(ui_SettingsScreen_Label_Label7, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);


ui_SettingsScreen_Container_ThemeRow = lv_obj_create(ui_SettingsScreen_Container_Container11);
lv_obj_remove_style_all(ui_SettingsScreen_Container_ThemeRow);
lv_obj_set_width( ui_SettingsScreen_Container_ThemeRow, lv_pct(100));
lv_obj_set_height( ui_SettingsScreen_Container_ThemeRow, LV_SIZE_CONTENT);
lv_obj_set_flex_flow(ui_SettingsScreen_Container_ThemeRow,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsScreen_Container_ThemeRow, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SettingsScreen_Container_ThemeRow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );
lv_obj_set_style_pad_row(ui_SettingsScreen_Container_ThemeRow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SettingsScreen_Container_ThemeRow, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsScreen_Switch_Theme_Label = lv_label_create(ui_SettingsScreen_Container_ThemeRow);
lv_label_set_text(ui_SettingsScreen_Switch_Theme_Label, "Theme:");
lv_obj_clear_flag(ui_SettingsScreen_Switch_Theme_Label, LV_OBJ_FLAG_HIDDEN);

ui_SettingsScreen_Switch_Theme = lv_switch_create(ui_SettingsScreen_Container_ThemeRow);
lv_obj_set_width(ui_SettingsScreen_Switch_Theme, 50);
lv_obj_set_height(ui_SettingsScreen_Switch_Theme, 25);
lv_obj_add_flag(ui_SettingsScreen_Switch_Theme, LV_OBJ_FLAG_CLICKABLE);
lv_obj_set_style_bg_color(ui_SettingsScreen_Switch_Theme,
    lv_palette_main(LV_PALETTE_GREEN),
    LV_PART_INDICATOR | LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_SettingsScreen_Switch_Theme,
    lv_palette_main(LV_PALETTE_BLUE),
    LV_PART_INDICATOR);
lv_obj_set_style_bg_color(ui_SettingsScreen_Switch_Theme,
    lv_palette_main(LV_PALETTE_GREY),
    LV_PART_MAIN);
lv_obj_set_style_outline_color(ui_SettingsScreen_Switch_Theme, lv_palette_main(LV_PALETTE_BLUE), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_clear_state(ui_SettingsScreen_Switch_Theme, LV_STATE_DISABLED);

ui_SettingsScreen_Container_AdhanRow = lv_obj_create(ui_SettingsScreen_Container_Container11);
lv_obj_remove_style_all(ui_SettingsScreen_Container_AdhanRow);
lv_obj_set_width( ui_SettingsScreen_Container_AdhanRow, lv_pct(100));
lv_obj_set_height( ui_SettingsScreen_Container_AdhanRow, LV_SIZE_CONTENT);
lv_obj_set_flex_flow(ui_SettingsScreen_Container_AdhanRow,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsScreen_Container_AdhanRow, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SettingsScreen_Container_AdhanRow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );
lv_obj_set_style_pad_row(ui_SettingsScreen_Container_AdhanRow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SettingsScreen_Container_AdhanRow, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsScreen_Label_AdhanLabel = lv_label_create(ui_SettingsScreen_Container_AdhanRow);
lv_label_set_text(ui_SettingsScreen_Label_AdhanLabel, "Adhan Ton");

ui_SettingsScreen_Button_AdhanChangeButton = lv_btn_create(ui_SettingsScreen_Container_AdhanRow);
lv_obj_set_width( ui_SettingsScreen_Button_AdhanChangeButton, 112);
lv_obj_set_height( ui_SettingsScreen_Button_AdhanChangeButton, 32);
lv_obj_clear_flag( ui_SettingsScreen_Button_AdhanChangeButton, LV_OBJ_FLAG_SCROLLABLE );

ui_SettingsScreen_Label_AdhanChangeLabel = lv_label_create(ui_SettingsScreen_Button_AdhanChangeButton);
lv_obj_set_align( ui_SettingsScreen_Label_AdhanChangeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsScreen_Label_AdhanChangeLabel,"Aendern");

}

void ui_Screen_SettingsScreen_screen_destroy(void)
{
   if (ui_Screen_SettingsScreen) lv_obj_del(ui_Screen_SettingsScreen);

// NULL screen variables
ui_Screen_SettingsScreen= NULL;
ui_SettingsScreen_Container_Container18= NULL;
ui_SettingsScreen_Button_ResetButton2= NULL;
ui_SettingsScreen_Label_Label5= NULL;
ui_SettingsScreen_Button_HomeButton= NULL;
ui_SettingsScreen_Label_Label3= NULL;
ui_SettingsScreen_Container_Container11= NULL;
ui_SettingsScreen_Label_SeetingsTitle= NULL;
ui_SettingsScreen_Label_Label6= NULL;
ui_SettingsScreen_Container_Container13= NULL;
ui_SettingsScreen_Button_SoundMinusButton= NULL;
ui_SettingsScreen_Label_Label9= NULL;
ui_SettingsScreen_Label_SoundLevelLabel= NULL;
ui_SettingsScreen_Button_SoundPlusButton1= NULL;
ui_SettingsScreen_Label_Label7= NULL;
ui_SettingsScreen_Container_ThemeRow= NULL;
ui_SettingsScreen_Switch_Theme= NULL;
ui_SettingsScreen_Switch_Theme_Label= NULL;
ui_SettingsScreen_Container_AdhanRow= NULL;
ui_SettingsScreen_Label_AdhanLabel= NULL;
ui_SettingsScreen_Button_AdhanChangeButton= NULL;
ui_SettingsScreen_Label_AdhanChangeLabel= NULL;

}
