// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen_HomeScreen = NULL;
lv_obj_t *ui_HomeScreen_Container_Container9 = NULL;
lv_obj_t *ui_HomeScreen_Container_WLAN_SD_Container = NULL;
lv_obj_t *ui_HomeScreen_Label_WLANStateLabel = NULL;
lv_obj_t *ui_HomeScreen_Label_SDStateLabel = NULL;
lv_obj_t *ui_HomeScreen_Label_DiffLabel = NULL;
lv_obj_t *ui_HomeScreen_Label_ClockLabel = NULL;
lv_obj_t *ui_HomeScreen_Label_DateLabel = NULL;
lv_obj_t *ui_HomeScreen_Container_Container10 = NULL;
lv_obj_t *ui_HomeScreen_Button_SettingsButton = NULL;
lv_obj_t *ui_HomeScreen_Label_Label1 = NULL;
lv_obj_t *ui_HomeScreen_Button_PrayersButton = NULL;
lv_obj_t *ui_HomeScreen_Label_Label4 = NULL;
// event funtions

// build funtions

void ui_Screen_HomeScreen_screen_init(void)
{
ui_Screen_HomeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_HomeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Screen_HomeScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_background);
ui_object_set_themeable_style_property(ui_Screen_HomeScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_background);

ui_HomeScreen_Container_Container9 = lv_obj_create(ui_Screen_HomeScreen);
lv_obj_remove_style_all(ui_HomeScreen_Container_Container9);
lv_obj_set_width( ui_HomeScreen_Container_Container9, lv_pct(90));
lv_obj_set_height( ui_HomeScreen_Container_Container9, lv_pct(70));
lv_obj_set_x( ui_HomeScreen_Container_Container9, 1 );
lv_obj_set_y( ui_HomeScreen_Container_Container9, -21 );
lv_obj_set_align( ui_HomeScreen_Container_Container9, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_HomeScreen_Container_Container9,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_HomeScreen_Container_Container9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_HomeScreen_Container_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomeScreen_Container_WLAN_SD_Container = lv_obj_create(ui_HomeScreen_Container_Container9);
lv_obj_remove_style_all(ui_HomeScreen_Container_WLAN_SD_Container);
lv_obj_set_width(ui_HomeScreen_Container_WLAN_SD_Container, lv_pct(100));
lv_obj_set_height(ui_HomeScreen_Container_WLAN_SD_Container, LV_SIZE_CONTENT);
lv_obj_set_style_pad_column(ui_HomeScreen_Container_WLAN_SD_Container, 10, 0);
lv_obj_set_flex_flow(ui_HomeScreen_Container_WLAN_SD_Container, LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_HomeScreen_Container_WLAN_SD_Container, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_HomeScreen_Container_WLAN_SD_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );

ui_HomeScreen_Label_WLANStateLabel = lv_label_create(ui_HomeScreen_Container_WLAN_SD_Container);
lv_obj_set_width( ui_HomeScreen_Label_WLANStateLabel, LV_SIZE_CONTENT);
lv_obj_set_height( ui_HomeScreen_Label_WLANStateLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_HomeScreen_Label_WLANStateLabel, LV_SYMBOL_WIFI);
lv_obj_set_style_text_color(ui_HomeScreen_Label_WLANStateLabel, lv_color_hex(0xFF0000), LV_PART_MAIN);
ui_object_set_themeable_style_property(ui_HomeScreen_Label_WLANStateLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_HomeScreen_Label_WLANStateLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_align(ui_HomeScreen_Label_WLANStateLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HomeScreen_Label_WLANStateLabel, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeScreen_Label_SDStateLabel = lv_label_create(ui_HomeScreen_Container_WLAN_SD_Container);
lv_obj_set_width( ui_HomeScreen_Label_SDStateLabel, LV_SIZE_CONTENT);
lv_obj_set_height( ui_HomeScreen_Label_SDStateLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_HomeScreen_Label_SDStateLabel, LV_SYMBOL_SD_CARD);
lv_obj_set_style_text_color(ui_HomeScreen_Label_SDStateLabel, lv_color_hex(0xFF0000), LV_PART_MAIN);
ui_object_set_themeable_style_property(ui_HomeScreen_Label_SDStateLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_HomeScreen_Label_SDStateLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_align(ui_HomeScreen_Label_SDStateLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HomeScreen_Label_SDStateLabel, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeScreen_Label_DiffLabel = lv_label_create(ui_HomeScreen_Container_Container9);
lv_obj_set_width( ui_HomeScreen_Label_DiffLabel, lv_pct(100));
lv_obj_set_height( ui_HomeScreen_Label_DiffLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HomeScreen_Label_DiffLabel, 11 );
lv_obj_set_y( ui_HomeScreen_Label_DiffLabel, 12 );
lv_obj_set_align( ui_HomeScreen_Label_DiffLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HomeScreen_Label_DiffLabel,"Asr in\n4:25");
ui_object_set_themeable_style_property(ui_HomeScreen_Label_DiffLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_primary);
ui_object_set_themeable_style_property(ui_HomeScreen_Label_DiffLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_primary);
lv_obj_set_style_text_align(ui_HomeScreen_Label_DiffLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HomeScreen_Label_DiffLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeScreen_Label_ClockLabel = lv_label_create(ui_HomeScreen_Container_Container9);
lv_obj_set_width( ui_HomeScreen_Label_ClockLabel, lv_pct(100));
lv_obj_set_height( ui_HomeScreen_Label_ClockLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HomeScreen_Label_ClockLabel, -10 );
lv_obj_set_y( ui_HomeScreen_Label_ClockLabel, -88 );
lv_obj_set_align( ui_HomeScreen_Label_ClockLabel, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_HomeScreen_Label_ClockLabel,"14:25:59");
ui_object_set_themeable_style_property(ui_HomeScreen_Label_ClockLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_HomeScreen_Label_ClockLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_align(ui_HomeScreen_Label_ClockLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HomeScreen_Label_ClockLabel, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeScreen_Label_DateLabel = lv_label_create(ui_HomeScreen_Container_Container9);
lv_obj_set_width( ui_HomeScreen_Label_DateLabel, lv_pct(100));
lv_obj_set_height( ui_HomeScreen_Label_DateLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HomeScreen_Label_DateLabel, -13 );
lv_obj_set_y( ui_HomeScreen_Label_DateLabel, -63 );
lv_obj_set_align( ui_HomeScreen_Label_DateLabel, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_HomeScreen_Label_DateLabel,"14.01.2026");
ui_object_set_themeable_style_property(ui_HomeScreen_Label_DateLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_HomeScreen_Label_DateLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_align(ui_HomeScreen_Label_DateLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HomeScreen_Label_DateLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeScreen_Container_Container10 = lv_obj_create(ui_Screen_HomeScreen);
lv_obj_remove_style_all(ui_HomeScreen_Container_Container10);
lv_obj_set_height( ui_HomeScreen_Container_Container10, 37);
lv_obj_set_width( ui_HomeScreen_Container_Container10, lv_pct(95));
lv_obj_set_x( ui_HomeScreen_Container_Container10, 0 );
lv_obj_set_y( ui_HomeScreen_Container_Container10, 94 );
lv_obj_set_align( ui_HomeScreen_Container_Container10, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_HomeScreen_Container_Container10,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_HomeScreen_Container_Container10, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_HomeScreen_Container_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_HomeScreen_Container_Container10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_HomeScreen_Container_Container10, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeScreen_Button_SettingsButton = lv_btn_create(ui_HomeScreen_Container_Container10);
lv_obj_set_width( ui_HomeScreen_Button_SettingsButton, 90);
lv_obj_set_height( ui_HomeScreen_Button_SettingsButton, 33);
lv_obj_set_x( ui_HomeScreen_Button_SettingsButton, 101 );
lv_obj_set_y( ui_HomeScreen_Button_SettingsButton, 96 );
lv_obj_set_align( ui_HomeScreen_Button_SettingsButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeScreen_Button_SettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HomeScreen_Button_SettingsButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_HomeScreen_Button_SettingsButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_background);
ui_object_set_themeable_style_property(ui_HomeScreen_Button_SettingsButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_background);
ui_object_set_themeable_style_property(ui_HomeScreen_Button_SettingsButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_primary);
ui_object_set_themeable_style_property(ui_HomeScreen_Button_SettingsButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_primary);
lv_obj_set_style_border_width(ui_HomeScreen_Button_SettingsButton, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_HomeScreen_Button_SettingsButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HomeScreen_Button_SettingsButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_primary);
ui_object_set_themeable_style_property(ui_HomeScreen_Button_SettingsButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_primary);

ui_HomeScreen_Label_Label1 = lv_label_create(ui_HomeScreen_Button_SettingsButton);
lv_obj_set_width( ui_HomeScreen_Label_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HomeScreen_Label_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_HomeScreen_Label_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_HomeScreen_Label_Label1,"Settings");

ui_HomeScreen_Button_PrayersButton = lv_btn_create(ui_HomeScreen_Container_Container10);
lv_obj_set_width( ui_HomeScreen_Button_PrayersButton, 90);
lv_obj_set_height( ui_HomeScreen_Button_PrayersButton, 33);
lv_obj_set_x( ui_HomeScreen_Button_PrayersButton, 0 );
lv_obj_set_y( ui_HomeScreen_Button_PrayersButton, 96 );
lv_obj_set_align( ui_HomeScreen_Button_PrayersButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeScreen_Button_PrayersButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HomeScreen_Button_PrayersButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_HomeScreen_Button_PrayersButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_primary);
ui_object_set_themeable_style_property(ui_HomeScreen_Button_PrayersButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_primary);
lv_obj_set_style_text_color(ui_HomeScreen_Button_PrayersButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HomeScreen_Button_PrayersButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeScreen_Label_Label4 = lv_label_create(ui_HomeScreen_Button_PrayersButton);
lv_obj_set_width( ui_HomeScreen_Label_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HomeScreen_Label_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_HomeScreen_Label_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_HomeScreen_Label_Label4,"Prayers");

}

void ui_Screen_HomeScreen_screen_destroy(void)
{
   if (ui_Screen_HomeScreen) lv_obj_del(ui_Screen_HomeScreen);

// NULL screen variables
ui_Screen_HomeScreen= NULL;
ui_HomeScreen_Container_Container9= NULL;
ui_HomeScreen_Container_WLAN_SD_Container = NULL;
ui_HomeScreen_Label_WLANStateLabel = NULL;
ui_HomeScreen_Label_SDStateLabel = NULL;
ui_HomeScreen_Label_DiffLabel= NULL;
ui_HomeScreen_Label_ClockLabel= NULL;
ui_HomeScreen_Label_DateLabel= NULL;
ui_HomeScreen_Container_Container10= NULL;
ui_HomeScreen_Button_SettingsButton= NULL;
ui_HomeScreen_Label_Label1= NULL;
ui_HomeScreen_Button_PrayersButton= NULL;
ui_HomeScreen_Label_Label4= NULL;

}
