// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen_PrayersScreen = NULL;lv_obj_t *ui_PrayersScreen_Container_Container1 = NULL;lv_obj_t *ui_PrayersScreen_Container_Container4 = NULL;lv_obj_t *ui_PrayersScreen_Label_PrayerLabel1 = NULL;lv_obj_t *ui_PrayersScreen_Label_ClockLabel6 = NULL;lv_obj_t *ui_PrayersScreen_Container_Container5 = NULL;lv_obj_t *ui_PrayersScreen_Label_PrayerLabel2 = NULL;lv_obj_t *ui_PrayersScreen_Label_ClockLabel3 = NULL;lv_obj_t *ui_PrayersScreen_Container_Container6 = NULL;lv_obj_t *ui_PrayersScreen_Label_PrayerLabel3 = NULL;lv_obj_t *ui_PrayersScreen_Label_ClockLabel5 = NULL;lv_obj_t *ui_PrayersScreen_Container_Container7 = NULL;lv_obj_t *ui_PrayersScreen_Label_PrayerLabel4 = NULL;lv_obj_t *ui_PrayersScreen_Label_ClockLabel8 = NULL;lv_obj_t *ui_PrayersScreen_Container_Container8 = NULL;lv_obj_t *ui_PrayersScreen_Label_PrayerLabel5 = NULL;lv_obj_t *ui_PrayersScreen_Label_ClockLabel10 = NULL;lv_obj_t *ui_PrayersScreen_Container_Container12 = NULL;lv_obj_t *ui_PrayersScreen_Button_HomeButton = NULL;lv_obj_t *ui_PrayersScreen_Label_Label2 = NULL;
// event funtions

// build funtions

void ui_Screen_PrayersScreen_screen_init(void)
{
ui_Screen_PrayersScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_PrayersScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Screen_PrayersScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_background);
ui_object_set_themeable_style_property(ui_Screen_PrayersScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_background);

ui_PrayersScreen_Container_Container1 = lv_obj_create(ui_Screen_PrayersScreen);
lv_obj_remove_style_all(ui_PrayersScreen_Container_Container1);
lv_obj_set_width( ui_PrayersScreen_Container_Container1, 260);
lv_obj_set_height( ui_PrayersScreen_Container_Container1, 198);
lv_obj_set_x( ui_PrayersScreen_Container_Container1, 0 );
lv_obj_set_y( ui_PrayersScreen_Container_Container1, -11 );
lv_obj_set_align( ui_PrayersScreen_Container_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PrayersScreen_Container_Container1,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_PrayersScreen_Container_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PrayersScreen_Container_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_PrayersScreen_Container_Container1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_PrayersScreen_Container_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrayersScreen_Container_Container4 = lv_obj_create(ui_PrayersScreen_Container_Container1);
lv_obj_remove_style_all(ui_PrayersScreen_Container_Container4);
lv_obj_set_height( ui_PrayersScreen_Container_Container4, 25);
lv_obj_set_width( ui_PrayersScreen_Container_Container4, lv_pct(80));
lv_obj_set_align( ui_PrayersScreen_Container_Container4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PrayersScreen_Container_Container4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PrayersScreen_Container_Container4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PrayersScreen_Container_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PrayersScreen_Label_PrayerLabel1 = lv_label_create(ui_PrayersScreen_Container_Container4);
lv_obj_set_width( ui_PrayersScreen_Label_PrayerLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrayersScreen_Label_PrayerLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PrayersScreen_Label_PrayerLabel1, -36 );
lv_obj_set_y( ui_PrayersScreen_Label_PrayerLabel1, -54 );
lv_obj_set_align( ui_PrayersScreen_Label_PrayerLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrayersScreen_Label_PrayerLabel1,"Fajr");
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_PrayerLabel1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_PrayerLabel1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_font(ui_PrayersScreen_Label_PrayerLabel1, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrayersScreen_Label_ClockLabel6 = lv_label_create(ui_PrayersScreen_Container_Container4);
lv_obj_set_width( ui_PrayersScreen_Label_ClockLabel6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrayersScreen_Label_ClockLabel6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PrayersScreen_Label_ClockLabel6, -36 );
lv_obj_set_y( ui_PrayersScreen_Label_ClockLabel6, -54 );
lv_obj_set_align( ui_PrayersScreen_Label_ClockLabel6, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrayersScreen_Label_ClockLabel6,"5:30");
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_ClockLabel6, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_ClockLabel6, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_font(ui_PrayersScreen_Label_ClockLabel6, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrayersScreen_Container_Container5 = lv_obj_create(ui_PrayersScreen_Container_Container1);
lv_obj_remove_style_all(ui_PrayersScreen_Container_Container5);
lv_obj_set_height( ui_PrayersScreen_Container_Container5, 25);
lv_obj_set_width( ui_PrayersScreen_Container_Container5, lv_pct(80));
lv_obj_set_align( ui_PrayersScreen_Container_Container5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PrayersScreen_Container_Container5,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PrayersScreen_Container_Container5, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PrayersScreen_Container_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PrayersScreen_Label_PrayerLabel2 = lv_label_create(ui_PrayersScreen_Container_Container5);
lv_obj_set_width( ui_PrayersScreen_Label_PrayerLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrayersScreen_Label_PrayerLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PrayersScreen_Label_PrayerLabel2, -36 );
lv_obj_set_y( ui_PrayersScreen_Label_PrayerLabel2, -54 );
lv_obj_set_align( ui_PrayersScreen_Label_PrayerLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrayersScreen_Label_PrayerLabel2,"Duhur");
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_PrayerLabel2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_PrayerLabel2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_font(ui_PrayersScreen_Label_PrayerLabel2, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrayersScreen_Label_ClockLabel3 = lv_label_create(ui_PrayersScreen_Container_Container5);
lv_obj_set_width( ui_PrayersScreen_Label_ClockLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrayersScreen_Label_ClockLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PrayersScreen_Label_ClockLabel3, -36 );
lv_obj_set_y( ui_PrayersScreen_Label_ClockLabel3, -54 );
lv_obj_set_align( ui_PrayersScreen_Label_ClockLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrayersScreen_Label_ClockLabel3,"12:10");
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_ClockLabel3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_ClockLabel3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_font(ui_PrayersScreen_Label_ClockLabel3, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrayersScreen_Container_Container6 = lv_obj_create(ui_PrayersScreen_Container_Container1);
lv_obj_remove_style_all(ui_PrayersScreen_Container_Container6);
lv_obj_set_height( ui_PrayersScreen_Container_Container6, 30);
lv_obj_set_width( ui_PrayersScreen_Container_Container6, lv_pct(80));
lv_obj_set_align( ui_PrayersScreen_Container_Container6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PrayersScreen_Container_Container6,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PrayersScreen_Container_Container6, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PrayersScreen_Container_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PrayersScreen_Label_PrayerLabel3 = lv_label_create(ui_PrayersScreen_Container_Container6);
lv_obj_set_width( ui_PrayersScreen_Label_PrayerLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrayersScreen_Label_PrayerLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PrayersScreen_Label_PrayerLabel3, -36 );
lv_obj_set_y( ui_PrayersScreen_Label_PrayerLabel3, -54 );
lv_obj_set_align( ui_PrayersScreen_Label_PrayerLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrayersScreen_Label_PrayerLabel3,"Asr");
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_PrayerLabel3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_primary);
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_PrayerLabel3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_primary);
lv_obj_set_style_text_font(ui_PrayersScreen_Label_PrayerLabel3, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrayersScreen_Label_ClockLabel5 = lv_label_create(ui_PrayersScreen_Container_Container6);
lv_obj_set_width( ui_PrayersScreen_Label_ClockLabel5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrayersScreen_Label_ClockLabel5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PrayersScreen_Label_ClockLabel5, -36 );
lv_obj_set_y( ui_PrayersScreen_Label_ClockLabel5, -54 );
lv_obj_set_align( ui_PrayersScreen_Label_ClockLabel5, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrayersScreen_Label_ClockLabel5,"12:10");
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_ClockLabel5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_primary);
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_ClockLabel5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_primary);
lv_obj_set_style_text_font(ui_PrayersScreen_Label_ClockLabel5, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrayersScreen_Container_Container7 = lv_obj_create(ui_PrayersScreen_Container_Container1);
lv_obj_remove_style_all(ui_PrayersScreen_Container_Container7);
lv_obj_set_height( ui_PrayersScreen_Container_Container7, 25);
lv_obj_set_width( ui_PrayersScreen_Container_Container7, lv_pct(80));
lv_obj_set_align( ui_PrayersScreen_Container_Container7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PrayersScreen_Container_Container7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PrayersScreen_Container_Container7, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PrayersScreen_Container_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PrayersScreen_Label_PrayerLabel4 = lv_label_create(ui_PrayersScreen_Container_Container7);
lv_obj_set_width( ui_PrayersScreen_Label_PrayerLabel4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrayersScreen_Label_PrayerLabel4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PrayersScreen_Label_PrayerLabel4, -36 );
lv_obj_set_y( ui_PrayersScreen_Label_PrayerLabel4, -54 );
lv_obj_set_align( ui_PrayersScreen_Label_PrayerLabel4, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrayersScreen_Label_PrayerLabel4,"Maghrib");
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_PrayerLabel4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_PrayerLabel4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_font(ui_PrayersScreen_Label_PrayerLabel4, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrayersScreen_Label_ClockLabel8 = lv_label_create(ui_PrayersScreen_Container_Container7);
lv_obj_set_width( ui_PrayersScreen_Label_ClockLabel8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrayersScreen_Label_ClockLabel8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PrayersScreen_Label_ClockLabel8, -36 );
lv_obj_set_y( ui_PrayersScreen_Label_ClockLabel8, -54 );
lv_obj_set_align( ui_PrayersScreen_Label_ClockLabel8, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrayersScreen_Label_ClockLabel8,"12:10");
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_ClockLabel8, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_ClockLabel8, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_font(ui_PrayersScreen_Label_ClockLabel8, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrayersScreen_Container_Container8 = lv_obj_create(ui_PrayersScreen_Container_Container1);
lv_obj_remove_style_all(ui_PrayersScreen_Container_Container8);
lv_obj_set_height( ui_PrayersScreen_Container_Container8, 25);
lv_obj_set_width( ui_PrayersScreen_Container_Container8, lv_pct(80));
lv_obj_set_align( ui_PrayersScreen_Container_Container8, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PrayersScreen_Container_Container8,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PrayersScreen_Container_Container8, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PrayersScreen_Container_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PrayersScreen_Label_PrayerLabel5 = lv_label_create(ui_PrayersScreen_Container_Container8);
lv_obj_set_width( ui_PrayersScreen_Label_PrayerLabel5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrayersScreen_Label_PrayerLabel5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PrayersScreen_Label_PrayerLabel5, -36 );
lv_obj_set_y( ui_PrayersScreen_Label_PrayerLabel5, -54 );
lv_obj_set_align( ui_PrayersScreen_Label_PrayerLabel5, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrayersScreen_Label_PrayerLabel5,"Isha");
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_PrayerLabel5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_PrayerLabel5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_font(ui_PrayersScreen_Label_PrayerLabel5, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrayersScreen_Label_ClockLabel10 = lv_label_create(ui_PrayersScreen_Container_Container8);
lv_obj_set_width( ui_PrayersScreen_Label_ClockLabel10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrayersScreen_Label_ClockLabel10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PrayersScreen_Label_ClockLabel10, -36 );
lv_obj_set_y( ui_PrayersScreen_Label_ClockLabel10, -54 );
lv_obj_set_align( ui_PrayersScreen_Label_ClockLabel10, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrayersScreen_Label_ClockLabel10,"12:10");
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_ClockLabel10, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_PrayersScreen_Label_ClockLabel10, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_font(ui_PrayersScreen_Label_ClockLabel10, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrayersScreen_Container_Container12 = lv_obj_create(ui_Screen_PrayersScreen);
lv_obj_remove_style_all(ui_PrayersScreen_Container_Container12);
lv_obj_set_height( ui_PrayersScreen_Container_Container12, 37);
lv_obj_set_width( ui_PrayersScreen_Container_Container12, lv_pct(95));
lv_obj_set_x( ui_PrayersScreen_Container_Container12, 0 );
lv_obj_set_y( ui_PrayersScreen_Container_Container12, 94 );
lv_obj_set_align( ui_PrayersScreen_Container_Container12, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PrayersScreen_Container_Container12,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PrayersScreen_Container_Container12, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PrayersScreen_Container_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_PrayersScreen_Container_Container12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_PrayersScreen_Container_Container12, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrayersScreen_Button_HomeButton = lv_btn_create(ui_PrayersScreen_Container_Container12);
lv_obj_set_width( ui_PrayersScreen_Button_HomeButton, 119);
lv_obj_set_height( ui_PrayersScreen_Button_HomeButton, 33);
lv_obj_set_x( ui_PrayersScreen_Button_HomeButton, 101 );
lv_obj_set_y( ui_PrayersScreen_Button_HomeButton, 96 );
lv_obj_set_align( ui_PrayersScreen_Button_HomeButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PrayersScreen_Button_HomeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PrayersScreen_Button_HomeButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_PrayersScreen_Button_HomeButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_background);
ui_object_set_themeable_style_property(ui_PrayersScreen_Button_HomeButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_background);
ui_object_set_themeable_style_property(ui_PrayersScreen_Button_HomeButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_primary);
ui_object_set_themeable_style_property(ui_PrayersScreen_Button_HomeButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_primary);
lv_obj_set_style_border_width(ui_PrayersScreen_Button_HomeButton, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PrayersScreen_Button_HomeButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_PrayersScreen_Button_HomeButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_primary);
ui_object_set_themeable_style_property(ui_PrayersScreen_Button_HomeButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_primary);

ui_PrayersScreen_Label_Label2 = lv_label_create(ui_PrayersScreen_Button_HomeButton);
lv_obj_set_width( ui_PrayersScreen_Label_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrayersScreen_Label_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PrayersScreen_Label_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrayersScreen_Label_Label2,"Back to Home");

}

void ui_Screen_PrayersScreen_screen_destroy(void)
{
   if (ui_Screen_PrayersScreen) lv_obj_del(ui_Screen_PrayersScreen);

// NULL screen variables
ui_Screen_PrayersScreen= NULL;
ui_PrayersScreen_Container_Container1= NULL;
ui_PrayersScreen_Container_Container4= NULL;
ui_PrayersScreen_Label_PrayerLabel1= NULL;
ui_PrayersScreen_Label_ClockLabel6= NULL;
ui_PrayersScreen_Container_Container5= NULL;
ui_PrayersScreen_Label_PrayerLabel2= NULL;
ui_PrayersScreen_Label_ClockLabel3= NULL;
ui_PrayersScreen_Container_Container6= NULL;
ui_PrayersScreen_Label_PrayerLabel3= NULL;
ui_PrayersScreen_Label_ClockLabel5= NULL;
ui_PrayersScreen_Container_Container7= NULL;
ui_PrayersScreen_Label_PrayerLabel4= NULL;
ui_PrayersScreen_Label_ClockLabel8= NULL;
ui_PrayersScreen_Container_Container8= NULL;
ui_PrayersScreen_Label_PrayerLabel5= NULL;
ui_PrayersScreen_Label_ClockLabel10= NULL;
ui_PrayersScreen_Container_Container12= NULL;
ui_PrayersScreen_Button_HomeButton= NULL;
ui_PrayersScreen_Label_Label2= NULL;

}
