// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN_STARTSCREEN_H
#define UI_SCREEN_STARTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_StartScreen
extern void ui_Screen_StartScreen_screen_init(void);
extern void ui_Screen_StartScreen_screen_destroy(void);
extern lv_obj_t *ui_Screen_StartScreen;
extern lv_obj_t *ui_StartScreen_Container_Container2;
extern lv_obj_t *ui_StartScreen_Label_SystemLoadingLabel1;
extern lv_obj_t *ui_StartScreen_Spinner_Spinner2;
extern lv_obj_t *ui_StartScreen_Label_StatusLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

