// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen_StartScreen = NULL;lv_obj_t *ui_StartScreen_Container_Container2 = NULL;lv_obj_t *ui_StartScreen_Label_SystemLoadingLabel1 = NULL;lv_obj_t *ui_StartScreen_Spinner_Spinner2 = NULL;lv_obj_t *ui_StartScreen_Label_StatusLabel = NULL;
// event funtions

// build funtions

void ui_Screen_StartScreen_screen_init(void)
{
ui_Screen_StartScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_StartScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Screen_StartScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_background);
ui_object_set_themeable_style_property(ui_Screen_StartScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_background);

ui_StartScreen_Container_Container2 = lv_obj_create(ui_Screen_StartScreen);
lv_obj_remove_style_all(ui_StartScreen_Container_Container2);
lv_obj_set_width( ui_StartScreen_Container_Container2, 237);
lv_obj_set_height( ui_StartScreen_Container_Container2, 186);
lv_obj_set_align( ui_StartScreen_Container_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_StartScreen_Container_Container2,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_StartScreen_Container_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_StartScreen_Container_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_StartScreen_Label_SystemLoadingLabel1 = lv_label_create(ui_StartScreen_Container_Container2);
lv_obj_set_width( ui_StartScreen_Label_SystemLoadingLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StartScreen_Label_SystemLoadingLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StartScreen_Label_SystemLoadingLabel1, 0 );
lv_obj_set_y( ui_StartScreen_Label_SystemLoadingLabel1, -60 );
lv_obj_set_align( ui_StartScreen_Label_SystemLoadingLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_StartScreen_Label_SystemLoadingLabel1,"System wird gestartet...");
ui_object_set_themeable_style_property(ui_StartScreen_Label_SystemLoadingLabel1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_primary);
ui_object_set_themeable_style_property(ui_StartScreen_Label_SystemLoadingLabel1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_primary);
lv_obj_set_style_text_font(ui_StartScreen_Label_SystemLoadingLabel1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_StartScreen_Label_SystemLoadingLabel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_StartScreen_Label_SystemLoadingLabel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_StartScreen_Label_SystemLoadingLabel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_StartScreen_Label_SystemLoadingLabel1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StartScreen_Spinner_Spinner2 = lv_spinner_create(ui_StartScreen_Container_Container2,1000,90);
lv_obj_set_width( ui_StartScreen_Spinner_Spinner2, 75);
lv_obj_set_height( ui_StartScreen_Spinner_Spinner2, 75);
lv_obj_set_x( ui_StartScreen_Spinner_Spinner2, -2 );
lv_obj_set_y( ui_StartScreen_Spinner_Spinner2, -10 );
lv_obj_set_align( ui_StartScreen_Spinner_Spinner2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_StartScreen_Spinner_Spinner2, LV_OBJ_FLAG_CLICKABLE );    /// Flags
ui_object_set_themeable_style_property(ui_StartScreen_Spinner_Spinner2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_gray);
ui_object_set_themeable_style_property(ui_StartScreen_Spinner_Spinner2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_gray);

ui_object_set_themeable_style_property(ui_StartScreen_Spinner_Spinner2, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_primary);
ui_object_set_themeable_style_property(ui_StartScreen_Spinner_Spinner2, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_primary);

ui_StartScreen_Label_StatusLabel = lv_label_create(ui_StartScreen_Container_Container2);
lv_obj_set_width( ui_StartScreen_Label_StatusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StartScreen_Label_StatusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StartScreen_Label_StatusLabel, 0 );
lv_obj_set_y( ui_StartScreen_Label_StatusLabel, 40 );
lv_obj_set_align( ui_StartScreen_Label_StatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_StartScreen_Label_StatusLabel,"Status Label");
ui_object_set_themeable_style_property(ui_StartScreen_Label_StatusLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_title);
ui_object_set_themeable_style_property(ui_StartScreen_Label_StatusLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_title);
lv_obj_set_style_text_font(ui_StartScreen_Label_StatusLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_StartScreen_Label_StatusLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_StartScreen_Label_StatusLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_StartScreen_Label_StatusLabel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_StartScreen_Label_StatusLabel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen_StartScreen_screen_destroy(void)
{
   if (ui_Screen_StartScreen) lv_obj_del(ui_Screen_StartScreen);

// NULL screen variables
ui_Screen_StartScreen= NULL;
ui_StartScreen_Container_Container2= NULL;
ui_StartScreen_Label_SystemLoadingLabel1= NULL;
ui_StartScreen_Spinner_Spinner2= NULL;
ui_StartScreen_Label_StatusLabel= NULL;

}
