// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN_PRAYERSSCREEN_H
#define UI_SCREEN_PRAYERSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_PrayersScreen
extern void ui_Screen_PrayersScreen_screen_init(void);
extern void ui_Screen_PrayersScreen_screen_destroy(void);
extern lv_obj_t *ui_Screen_PrayersScreen;
extern lv_obj_t *ui_PrayersScreen_Container_Container1;
extern lv_obj_t *ui_PrayersScreen_Container_Container4;
extern lv_obj_t *ui_PrayersScreen_Label_PrayerLabel1;
extern lv_obj_t *ui_PrayersScreen_Label_ClockLabel6;
extern lv_obj_t *ui_PrayersScreen_Container_Container5;
extern lv_obj_t *ui_PrayersScreen_Label_PrayerLabel2;
extern lv_obj_t *ui_PrayersScreen_Label_ClockLabel3;
extern lv_obj_t *ui_PrayersScreen_Container_Container6;
extern lv_obj_t *ui_PrayersScreen_Label_PrayerLabel3;
extern lv_obj_t *ui_PrayersScreen_Label_ClockLabel5;
extern lv_obj_t *ui_PrayersScreen_Container_Container7;
extern lv_obj_t *ui_PrayersScreen_Label_PrayerLabel4;
extern lv_obj_t *ui_PrayersScreen_Label_ClockLabel8;
extern lv_obj_t *ui_PrayersScreen_Container_Container8;
extern lv_obj_t *ui_PrayersScreen_Label_PrayerLabel5;
extern lv_obj_t *ui_PrayersScreen_Label_ClockLabel10;
extern lv_obj_t *ui_PrayersScreen_Container_Container12;
extern lv_obj_t *ui_PrayersScreen_Button_HomeButton;
extern lv_obj_t *ui_PrayersScreen_Label_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

