// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN_HOMESCREEN_H
#define UI_SCREEN_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_HomeScreen
extern void ui_Screen_HomeScreen_screen_init(void);
extern void ui_Screen_HomeScreen_screen_destroy(void);
extern lv_obj_t *ui_Screen_HomeScreen;
extern lv_obj_t *ui_HomeScreen_Container_Container9;
extern lv_obj_t *ui_HomeScreen_Container_WLAN_SD_Container;
extern lv_obj_t *ui_HomeScreen_Label_WLANStateLabel;
extern lv_obj_t *ui_HomeScreen_Label_SDStateLabel;
extern lv_obj_t *ui_HomeScreen_Label_DiffLabel;
extern lv_obj_t *ui_HomeScreen_Label_ClockLabel;
extern lv_obj_t *ui_HomeScreen_Label_DateLabel;
extern lv_obj_t *ui_HomeScreen_Container_Container10;
extern lv_obj_t *ui_HomeScreen_Button_SettingsButton;
extern lv_obj_t *ui_HomeScreen_Label_Label1;
extern lv_obj_t *ui_HomeScreen_Button_PrayersButton;
extern lv_obj_t *ui_HomeScreen_Label_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

