// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_primary[3] = {0x2DA041, 0xC9A227, 0x2DA041};
const ui_theme_variable_t _ui_theme_alpha_primary[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_secondary[3] = {0x80C78C, 0xFFFAE9, 0x80C78C};
const ui_theme_variable_t _ui_theme_alpha_secondary[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_background[3] = {0xFFFFFF, 0x000000, 0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_background[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_gray[3] = {0xBBBBBB, 0xBBBBBB, 0xBBBBBB};
const ui_theme_variable_t _ui_theme_alpha_gray[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_title[3] = {0x000000, 0xFFFFFF, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_title[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_LIGHT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}
